-- ============================================
-- Etapa 1 – Migração de Matrículas
-- Criação da tabela public.matriculas
-- Ajustes na tabela public.turma_aluno
-- ============================================

-- 1) TIPOS ENUM (somente se ainda não existirem)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tipo_matricula_enum') THEN
    CREATE TYPE tipo_matricula_enum AS ENUM ('REGULAR', 'CURSO_LIVRE', 'PROJETO_ARTISTICO');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'status_matricula_enum') THEN
    CREATE TYPE status_matricula_enum AS ENUM ('ATIVA', 'TRANCADA', 'CANCELADA', 'CONCLUIDA');
  END IF;
END$$;

-- 2) TABELA MATRICULAS
CREATE TABLE IF NOT EXISTS public.matriculas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pessoa_id BIGINT NOT NULL,
  responsavel_financeiro_id BIGINT NOT NULL,
  tipo_matricula tipo_matricula_enum NOT NULL,
  vinculo_id BIGINT NOT NULL,
  plano_matricula_id BIGINT NOT NULL,
  contrato_modelo_id BIGINT NOT NULL,
  contrato_emitido_id BIGINT,
  contrato_pdf_url TEXT,
  status status_matricula_enum NOT NULL,
  ano_referencia INTEGER,
  data_matricula DATE NOT NULL DEFAULT CURRENT_DATE,
  data_encerramento DATE,
  observacoes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by UUID,
  updated_by UUID
);

-- 3) FKs OBRIGATÓRIAS (tabelas já existentes)
DO $$
BEGIN
  -- pessoa_id -> pessoas.id
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'matriculas_pessoa_id_fkey'
  ) THEN
    ALTER TABLE public.matriculas
      ADD CONSTRAINT matriculas_pessoa_id_fkey
      FOREIGN KEY (pessoa_id) REFERENCES public.pessoas(id)
      ON UPDATE CASCADE ON DELETE RESTRICT;
  END IF;

  -- responsavel_financeiro_id -> pessoas.id
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'matriculas_responsavel_financeiro_id_fkey'
  ) THEN
    ALTER TABLE public.matriculas
      ADD CONSTRAINT matriculas_responsavel_financeiro_id_fkey
      FOREIGN KEY (responsavel_financeiro_id) REFERENCES public.pessoas(id)
      ON UPDATE CASCADE ON DELETE RESTRICT;
  END IF;

  -- vinculo_id -> turmas.turma_id
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'matriculas_vinculo_id_fkey'
  ) THEN
    ALTER TABLE public.matriculas
      ADD CONSTRAINT matriculas_vinculo_id_fkey
      FOREIGN KEY (vinculo_id) REFERENCES public.turmas(turma_id)
      ON UPDATE CASCADE ON DELETE RESTRICT;
  END IF;
END$$;

-- 3.1) FKs opcionais (só se as tabelas existirem)
DO $$
BEGIN
  -- plano_matricula_id -> planos_matricula.id
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'planos_matricula'
  )
  AND NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'matriculas_plano_matricula_id_fkey'
  ) THEN
    ALTER TABLE public.matriculas
      ADD CONSTRAINT matriculas_plano_matricula_id_fkey
      FOREIGN KEY (plano_matricula_id) REFERENCES public.planos_matricula(id)
      ON UPDATE CASCADE ON DELETE RESTRICT;
  END IF;

  -- contrato_modelo_id -> contratos_modelo.id
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'contratos_modelo'
  )
  AND NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'matriculas_contrato_modelo_id_fkey'
  ) THEN
    ALTER TABLE public.matriculas
      ADD CONSTRAINT matriculas_contrato_modelo_id_fkey
      FOREIGN KEY (contrato_modelo_id) REFERENCES public.contratos_modelo(id)
      ON UPDATE CASCADE ON DELETE RESTRICT;
  END IF;

  -- contrato_emitido_id -> contratos_emitidos.id
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'contratos_emitidos'
  )
  AND NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'matriculas_contrato_emitido_id_fkey'
  ) THEN
    ALTER TABLE public.matriculas
      ADD CONSTRAINT matriculas_contrato_emitido_id_fkey
      FOREIGN KEY (contrato_emitido_id) REFERENCES public.contratos_emitidos(id)
      ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
END$$;

-- 4) ÍNDICES EM MATRICULAS
CREATE INDEX IF NOT EXISTS idx_matriculas_pessoa
  ON public.matriculas (pessoa_id);

CREATE INDEX IF NOT EXISTS idx_matriculas_responsavel
  ON public.matriculas (responsavel_financeiro_id);

CREATE INDEX IF NOT EXISTS idx_matriculas_status
  ON public.matriculas (status);

CREATE INDEX IF NOT EXISTS idx_matriculas_tipo_ano
  ON public.matriculas (tipo_matricula, ano_referencia);

CREATE INDEX IF NOT EXISTS idx_matriculas_vinculo
  ON public.matriculas (vinculo_id);

-- Regra de unicidade para matrícula REGULAR por turma
CREATE UNIQUE INDEX IF NOT EXISTS uniq_matriculas_pessoa_tipo_vinculo_regular
  ON public.matriculas (pessoa_id, tipo_matricula, vinculo_id)
  WHERE tipo_matricula = 'REGULAR';

-- ============================================
-- 5) AJUSTES NA TABELA TURMA_ALUNO
-- ============================================

-- 5.1) Garantir FK explícita aluno_pessoa_id -> pessoas.id
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'turma_aluno_aluno_pessoa_id_fkey'
  ) THEN
    ALTER TABLE public.turma_aluno
      ADD CONSTRAINT turma_aluno_aluno_pessoa_id_fkey
      FOREIGN KEY (aluno_pessoa_id) REFERENCES public.pessoas(id)
      ON UPDATE CASCADE ON DELETE RESTRICT;
  END IF;
END$$;

-- 5.2) Adicionar coluna matricula_id, se ainda não existir
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'turma_aluno'
      AND column_name = 'matricula_id'
  ) THEN
    ALTER TABLE public.turma_aluno
      ADD COLUMN matricula_id BIGINT NULL;
  END IF;
END$$;

-- 5.3) FK matricula_id -> matriculas(id)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'turma_aluno_matricula_id_fkey'
  ) THEN
    ALTER TABLE public.turma_aluno
      ADD CONSTRAINT turma_aluno_matricula_id_fkey
      FOREIGN KEY (matricula_id) REFERENCES public.matriculas(id)
      ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
END$$;

-- 5.4) Índices de apoio em turma_aluno
CREATE INDEX IF NOT EXISTS idx_turma_aluno_matricula
  ON public.turma_aluno (matricula_id);

CREATE INDEX IF NOT EXISTS idx_turma_aluno_pessoa
  ON public.turma_aluno (aluno_pessoa_id);

-- 5.5) (Opcional FUTURO) Unique 1:1 matrícula x turma
-- Deixar comentado por enquanto; só ativar depois de analisar dados reais.
-- CREATE UNIQUE INDEX uniq_turma_aluno_matricula_turma
--   ON public.turma_aluno (matricula_id, turma_id)
--   WHERE matricula_id IS NOT NULL;

-- ============================================
-- FIM DA MIGRATION DA ETAPA 1
-- ============================================
