-- =========================================
-- MODULO: FREQUENCIA (Diario do Professor) - Etapa 1 (SQL)
-- Objetivo:
--  - Registrar aulas/sessoes por turma
--  - Registrar presenca por aluno (pessoa) em cada aula
-- Dependencias esperadas:
--  - public.turmas (PK: turma_id)
--  - public.pessoas (PK: id)
-- Observacao:
--  - RLS sera habilitado, mas as politicas serao tratadas na fase API.
-- =========================================

begin;

-- 1) Tipo (enum) do status de presenca
do $$
begin
  if not exists (select 1 from pg_type where typname = 'frequencia_status') then
    create type public.frequencia_status as enum (
      'PRESENTE',
      'FALTA',
      'JUSTIFICADA',
      'ATRASO'
    );
  end if;
end $$;

-- 2) Tabela de aulas/sessoes da turma
create table if not exists public.turma_aulas (
  id bigint generated by default as identity primary key,
  turma_id bigint not null,
  data_aula date not null,
  hora_inicio time null,
  hora_fim time null,
  conteudo text null,
  observacoes text null,
  criado_por uuid null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint turma_aulas_turma_id_fk
    foreign key (turma_id) references public.turmas(turma_id) on delete cascade,
  constraint turma_aulas_unq_turma_data
    unique (turma_id, data_aula)
);

create index if not exists idx_turma_aulas_turma_id on public.turma_aulas (turma_id);
create index if not exists idx_turma_aulas_data_aula on public.turma_aulas (data_aula);

-- Trigger simples de updated_at
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_turma_aulas_updated_at on public.turma_aulas;
create trigger trg_turma_aulas_updated_at
before update on public.turma_aulas
for each row execute function public.set_updated_at();

-- 3) Presencas por aula (1 linha por aluno/pessoa)
create table if not exists public.turma_aula_presencas (
  id bigint generated by default as identity primary key,
  aula_id bigint not null,
  aluno_pessoa_id bigint not null,
  status public.frequencia_status not null,
  minutos_atraso integer null,
  observacao text null,
  registrado_por uuid null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint turma_aula_presencas_aula_fk
    foreign key (aula_id) references public.turma_aulas(id) on delete cascade,
  constraint turma_aula_presencas_aluno_fk
    foreign key (aluno_pessoa_id) references public.pessoas(id) on delete restrict,
  constraint turma_aula_presencas_unq_aula_aluno
    unique (aula_id, aluno_pessoa_id),
  constraint turma_aula_presencas_chk_atraso
    check (
      (status <> 'ATRASO' and minutos_atraso is null)
      or
      (status = 'ATRASO' and minutos_atraso is not null and minutos_atraso >= 1)
    )
);

create index if not exists idx_turma_aula_presencas_aula_id on public.turma_aula_presencas (aula_id);
create index if not exists idx_turma_aula_presencas_aluno_id on public.turma_aula_presencas (aluno_pessoa_id);
create index if not exists idx_turma_aula_presencas_status on public.turma_aula_presencas (status);

drop trigger if exists trg_turma_aula_presencas_updated_at on public.turma_aula_presencas;
create trigger trg_turma_aula_presencas_updated_at
before update on public.turma_aula_presencas
for each row execute function public.set_updated_at();

-- 4) RLS (habilitar agora; politicas entram na fase API)
alter table public.turma_aulas enable row level security;
alter table public.turma_aula_presencas enable row level security;

commit;
