begin;

-- =========================================================
-- 0) Garantir Aula # na Sessao Pedagogica (turma_aulas)
-- =========================================================
alter table public.turma_aulas
  add column if not exists aula_numero integer null;

create index if not exists idx_turma_aulas_turma_aula_numero
  on public.turma_aulas (turma_id, aula_numero);

-- =========================================================
-- 1) ENUMS
-- =========================================================
do $$
begin
  if not exists (select 1 from pg_type where typname = 'planejamento_ciclo_status') then
    create type public.planejamento_ciclo_status as enum ('RASCUNHO','APROVADO','EM_EXECUCAO','ENCERRADO');
  end if;

  if not exists (select 1 from pg_type where typname = 'nivel_abordagem') then
    create type public.nivel_abordagem as enum ('INTRODUCAO','PRATICA','REFORCO','CONSOLIDACAO');
  end if;

  if not exists (select 1 from pg_type where typname = 'plano_sessao_status') then
    create type public.plano_sessao_status as enum ('EM_EXECUCAO','CONCLUIDO');
  end if;
end $$;

-- =========================================================
-- 2) MAPA PEDAGOGICO (normativo)
-- Depende das tabelas existentes: cursos, niveis, modulos, habilidades
-- =========================================================
create table if not exists public.mapas_pedagogicos (
  id bigint generated by default as identity primary key,
  curso_id bigint not null,
  nivel_id bigint not null,
  descricao text null,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  updated_by uuid null,
  constraint mapas_pedagogicos_curso_fk foreign key (curso_id) references public.cursos(id) on delete restrict,
  constraint mapas_pedagogicos_nivel_fk foreign key (nivel_id) references public.niveis(id) on delete restrict,
  constraint mapas_pedagogicos_unq unique (curso_id, nivel_id)
);

create table if not exists public.mapa_modulos (
  id bigint generated by default as identity primary key,
  mapa_id bigint not null,
  modulo_id bigint not null,
  obrigatorio boolean not null default true,
  ordem integer null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  updated_by uuid null,
  constraint mapa_modulos_mapa_fk foreign key (mapa_id) references public.mapas_pedagogicos(id) on delete cascade,
  constraint mapa_modulos_modulo_fk foreign key (modulo_id) references public.modulos(id) on delete restrict,
  constraint mapa_modulos_unq unique (mapa_id, modulo_id)
);

create table if not exists public.mapa_habilidades (
  id bigint generated by default as identity primary key,
  mapa_modulo_id bigint not null,
  habilidade_id bigint not null,
  obrigatoria boolean not null default true,
  peso_pedagogico numeric null,
  ordem integer null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  updated_by uuid null,
  constraint mapa_habilidades_mapa_modulo_fk foreign key (mapa_modulo_id) references public.mapa_modulos(id) on delete cascade,
  constraint mapa_habilidades_habilidade_fk foreign key (habilidade_id) references public.habilidades(id) on delete restrict,
  constraint mapa_habilidades_unq unique (mapa_modulo_id, habilidade_id)
);

-- =========================================================
-- 3) CICLOS DE PLANEJAMENTO (reunioes)
-- =========================================================
create table if not exists public.planejamento_ciclos (
  id bigint generated by default as identity primary key,
  turma_id bigint not null,
  titulo text not null,
  aula_inicio_numero integer not null,
  aula_fim_numero integer not null,
  status public.planejamento_ciclo_status not null default 'RASCUNHO',
  aprovado_por uuid null,
  aprovado_em timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  updated_by uuid null,
  constraint planejamento_ciclos_turma_fk foreign key (turma_id) references public.turmas(turma_id) on delete cascade,
  constraint planejamento_ciclos_chk_intervalo check (aula_inicio_numero >= 1 and aula_fim_numero >= aula_inicio_numero)
);

create index if not exists idx_planejamento_ciclos_turma_status on public.planejamento_ciclos (turma_id, status);

-- =========================================================
-- 4) PLANO DE AULA (por Aula #)
-- =========================================================
create table if not exists public.planos_aula (
  id bigint generated by default as identity primary key,
  ciclo_id bigint not null,
  aula_numero integer not null,
  intencao_pedagogica text null,
  observacoes_gerais text null,
  playlist_url text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  updated_by uuid null,
  constraint planos_aula_ciclo_fk foreign key (ciclo_id) references public.planejamento_ciclos(id) on delete cascade,
  constraint planos_aula_unq unique (ciclo_id, aula_numero)
);

create table if not exists public.plano_aula_blocos (
  id bigint generated by default as identity primary key,
  plano_aula_id bigint not null,
  ordem integer not null,
  titulo text not null,
  objetivo text null,
  minutos_min integer null,
  minutos_ideal integer null,
  minutos_max integer null,
  musica_sugestao text null,
  observacoes text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  updated_by uuid null,
  constraint plano_aula_blocos_plano_fk foreign key (plano_aula_id) references public.planos_aula(id) on delete cascade
);

create index if not exists idx_plano_aula_blocos_plano_ordem on public.plano_aula_blocos (plano_aula_id, ordem);

create table if not exists public.plano_aula_subblocos (
  id bigint generated by default as identity primary key,
  bloco_id bigint not null,
  ordem integer not null,
  titulo text not null,
  minutos_min integer null,
  minutos_ideal integer null,
  minutos_max integer null,
  habilidade_id bigint null,
  nivel_abordagem public.nivel_abordagem null,
  instrucoes text null,
  musica_sugestao text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  updated_by uuid null,
  constraint plano_aula_subblocos_bloco_fk foreign key (bloco_id) references public.plano_aula_blocos(id) on delete cascade,
  constraint plano_aula_subblocos_habilidade_fk foreign key (habilidade_id) references public.habilidades(id) on delete set null
);

create index if not exists idx_plano_aula_subblocos_bloco_ordem on public.plano_aula_subblocos (bloco_id, ordem);

-- =========================================================
-- 5) INSTANCIA DO PLANO NA SESSAO (execucao real)
-- =========================================================
create table if not exists public.plano_aula_instancias (
  id bigint generated by default as identity primary key,
  turma_aula_id bigint not null,
  plano_aula_id bigint not null,
  status public.plano_sessao_status not null default 'EM_EXECUCAO',
  notas_pos_aula text null,
  concluido_por uuid null,
  concluido_em timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  updated_by uuid null,
  constraint plano_aula_instancias_turma_aula_fk foreign key (turma_aula_id) references public.turma_aulas(id) on delete cascade,
  constraint plano_aula_instancias_plano_fk foreign key (plano_aula_id) references public.planos_aula(id) on delete restrict,
  constraint plano_aula_instancias_unq unique (turma_aula_id)
);

-- updated_at triggers (reusar set_updated_at ja existente)
drop trigger if exists trg_mapas_pedagogicos_updated_at on public.mapas_pedagogicos;
create trigger trg_mapas_pedagogicos_updated_at before update on public.mapas_pedagogicos
for each row execute function public.set_updated_at();

drop trigger if exists trg_mapa_modulos_updated_at on public.mapa_modulos;
create trigger trg_mapa_modulos_updated_at before update on public.mapa_modulos
for each row execute function public.set_updated_at();

drop trigger if exists trg_mapa_habilidades_updated_at on public.mapa_habilidades;
create trigger trg_mapa_habilidades_updated_at before update on public.mapa_habilidades
for each row execute function public.set_updated_at();

drop trigger if exists trg_planejamento_ciclos_updated_at on public.planejamento_ciclos;
create trigger trg_planejamento_ciclos_updated_at before update on public.planejamento_ciclos
for each row execute function public.set_updated_at();

drop trigger if exists trg_planos_aula_updated_at on public.planos_aula;
create trigger trg_planos_aula_updated_at before update on public.planos_aula
for each row execute function public.set_updated_at();

drop trigger if exists trg_plano_aula_blocos_updated_at on public.plano_aula_blocos;
create trigger trg_plano_aula_blocos_updated_at before update on public.plano_aula_blocos
for each row execute function public.set_updated_at();

drop trigger if exists trg_plano_aula_subblocos_updated_at on public.plano_aula_subblocos;
create trigger trg_plano_aula_subblocos_updated_at before update on public.plano_aula_subblocos
for each row execute function public.set_updated_at();

drop trigger if exists trg_plano_aula_instancias_updated_at on public.plano_aula_instancias;
create trigger trg_plano_aula_instancias_updated_at before update on public.plano_aula_instancias
for each row execute function public.set_updated_at();

commit;
