create table if not exists public.escola_config_financeira (
  id bigint generated by default as identity primary key,
  centro_custo_padrao_escola_id bigint null references public.centros_custo(id) on delete set null,
  centro_custo_intermediacao_financeira_id bigint null references public.centros_custo(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists escola_config_financeira_singleton
  on public.escola_config_financeira ((1));

-- garante 1 linha (singleton)
insert into public.escola_config_financeira (id)
select 1
where not exists (select 1 from public.escola_config_financeira where id = 1);

select pg_notify('pgrst', 'reload schema');
