BEGIN;

-- Criar tabela de Tabela de Matricula (precificacao oficial)
CREATE TABLE IF NOT EXISTS public.matricula_tabelas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  produto_tipo TEXT NOT NULL,
  referencia_tipo TEXT NOT NULL,
  referencia_id BIGINT NOT NULL,
  ano_referencia INTEGER,
  titulo TEXT NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by UUID,
  updated_by UUID
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'matricula_tabelas_produto_tipo_chk'
      AND conrelid = 'public.matricula_tabelas'::regclass
  ) THEN
    ALTER TABLE public.matricula_tabelas
      ADD CONSTRAINT matricula_tabelas_produto_tipo_chk
      CHECK (produto_tipo IN ('REGULAR','CURSO_LIVRE','PROJETO_ARTISTICO'));
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'matricula_tabelas_referencia_tipo_chk'
      AND conrelid = 'public.matricula_tabelas'::regclass
  ) THEN
    ALTER TABLE public.matricula_tabelas
      ADD CONSTRAINT matricula_tabelas_referencia_tipo_chk
      CHECK (referencia_tipo IN ('TURMA','PRODUTO','PROJETO'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_matricula_tabelas_ativo
  ON public.matricula_tabelas (ativo);

CREATE INDEX IF NOT EXISTS idx_matricula_tabelas_produto
  ON public.matricula_tabelas (produto_tipo);

CREATE INDEX IF NOT EXISTS idx_matricula_tabelas_ref
  ON public.matricula_tabelas (referencia_tipo, referencia_id);

CREATE INDEX IF NOT EXISTS idx_matricula_tabelas_ano
  ON public.matricula_tabelas (ano_referencia);

COMMIT;
