------------------------------------------------------------
-- 1. Garantir colunas de quantidade pedida/recebida em itens
------------------------------------------------------------
ALTER TABLE public.loja_pedidos_compra_itens
  ADD COLUMN IF NOT EXISTS quantidade_pedida integer NOT NULL DEFAULT 0;

ALTER TABLE public.loja_pedidos_compra_itens
  ADD COLUMN IF NOT EXISTS quantidade_recebida integer NOT NULL DEFAULT 0;

------------------------------------------------------------
-- 2. Tabela de recebimentos parciais de compra
------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.loja_pedidos_compra_recebimentos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id bigint NOT NULL,
  item_id bigint NOT NULL,
  produto_id bigint NOT NULL,
  quantidade integer NOT NULL CHECK (quantidade > 0),
  data_recebimento date NOT NULL DEFAULT CURRENT_DATE,
  observacao text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid
);

-- FKs (usar ON DELETE CASCADE para não sobrar lixo se o pedido for apagado em dev)
ALTER TABLE public.loja_pedidos_compra_recebimentos
  ADD CONSTRAINT loja_pedidos_compra_recebimentos_pedido_id_fkey
  FOREIGN KEY (pedido_id)
  REFERENCES public.loja_pedidos_compra(id)
  ON UPDATE CASCADE
  ON DELETE CASCADE;

ALTER TABLE public.loja_pedidos_compra_recebimentos
  ADD CONSTRAINT loja_pedidos_compra_recebimentos_item_id_fkey
  FOREIGN KEY (item_id)
  REFERENCES public.loja_pedidos_compra_itens(id)
  ON UPDATE CASCADE
  ON DELETE CASCADE;

ALTER TABLE public.loja_pedidos_compra_recebimentos
  ADD CONSTRAINT loja_pedidos_compra_recebimentos_produto_id_fkey
  FOREIGN KEY (produto_id)
  REFERENCES public.loja_produtos(id)
  ON UPDATE CASCADE
  ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS idx_loja_pedidos_compra_recebimentos_pedido
  ON public.loja_pedidos_compra_recebimentos (pedido_id);

------------------------------------------------------------
-- 3. Flag de bloqueio para venda em produtos
------------------------------------------------------------
ALTER TABLE public.loja_produtos
  ADD COLUMN IF NOT EXISTS bloqueado_para_venda boolean NOT NULL DEFAULT false;

------------------------------------------------------------
-- Fim da migration
------------------------------------------------------------
