BEGIN;

CREATE TABLE IF NOT EXISTS public.matricula_tabela_itens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tabela_id BIGINT NOT NULL REFERENCES public.matricula_tabelas(id) ON DELETE CASCADE,
  codigo_item TEXT NOT NULL,
  descricao TEXT,
  tipo_item TEXT NOT NULL,
  valor_centavos INTEGER NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT true,
  ordem INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by UUID,
  updated_by UUID
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'matricula_tabela_itens_tipo_item_chk'
      AND conrelid = 'public.matricula_tabela_itens'::regclass
  ) THEN
    ALTER TABLE public.matricula_tabela_itens
      ADD CONSTRAINT matricula_tabela_itens_tipo_item_chk
      CHECK (tipo_item IN ('RECORRENTE','UNICO','EVENTUAL'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_matricula_tabela_itens_tabela
  ON public.matricula_tabela_itens (tabela_id);

CREATE INDEX IF NOT EXISTS idx_matricula_tabela_itens_ativo
  ON public.matricula_tabela_itens (ativo);

CREATE INDEX IF NOT EXISTS idx_matricula_tabela_itens_codigo
  ON public.matricula_tabela_itens (codigo_item);

CREATE INDEX IF NOT EXISTS idx_matricula_tabela_itens_ordem
  ON public.matricula_tabela_itens (ordem);

COMMIT;
