-- Loja v1 — Variantes com cadastros (modelo correto)
-- Data: 2025-12-13
-- Objetivo: dicionários (marca/cor/numeracao/tamanho/modelo) + variantes com FKs.
-- Nota: mantém Loja v0 funcionando. Integração no caixa fica para etapa posterior.

begin;

-- =========================================
-- 1) Dicionários (cadastros)
-- =========================================

create table if not exists public.loja_marcas (
id bigint generated by default as identity primary key,
nome text not null,
ativo boolean not null default true,
created_at timestamptz not null default now(),
updated_at timestamptz not null default now()
);
create unique index if not exists ux_loja_marcas_nome
on public.loja_marcas (upper(trim(nome)));

create table if not exists public.loja_cores (
id bigint generated by default as identity primary key,
nome text not null, -- "Rosa", "Preto", "Nude"
codigo text, -- opcional: "ROS", "PRE", etc.
hex text, -- opcional: "#FFB6C1"
ativo boolean not null default true,
created_at timestamptz not null default now(),
updated_at timestamptz not null default now()
);
create unique index if not exists ux_loja_cores_nome
on public.loja_cores (upper(trim(nome)));

create table if not exists public.loja_numeracoes (
id bigint generated by default as identity primary key,
valor integer not null, -- 36, 37, 38...
tipo text not null default 'CALCADO', -- futuro: CALCADO, MEIA, etc.
ativo boolean not null default true,
created_at timestamptz not null default now(),
updated_at timestamptz not null default now()
);
create unique index if not exists ux_loja_numeracoes_tipo_valor
on public.loja_numeracoes (tipo, valor);

create table if not exists public.loja_tamanhos (
id bigint generated by default as identity primary key,
nome text not null, -- "P", "M", "G", "10 anos"
tipo text not null default 'ROUPA', -- futuro: ROUPA, MEIA, OUTRO
ordem integer not null default 0,
ativo boolean not null default true,
created_at timestamptz not null default now(),
updated_at timestamptz not null default now()
);
create unique index if not exists ux_loja_tamanhos_tipo_nome
on public.loja_tamanhos (tipo, upper(trim(nome)));

create table if not exists public.loja_modelos (
id bigint generated by default as identity primary key,
nome text not null, -- "Meia Ponta", "Ponta", "Básico"
ativo boolean not null default true,
created_at timestamptz not null default now(),
updated_at timestamptz not null default now()
);
create unique index if not exists ux_loja_modelos_nome
on public.loja_modelos (upper(trim(nome)));

-- =========================================
-- 2) Extensões mínimas em loja_produtos (produto base)
-- =========================================
alter table public.loja_produtos
add column if not exists marca_id bigint,
add column if not exists modelo_id bigint;

do $$
begin
if not exists (select 1 from pg_constraint where conname = 'fk_loja_produtos_marca_id') then
alter table public.loja_produtos
add constraint fk_loja_produtos_marca_id
foreign key (marca_id) references public.loja_marcas(id)
on delete set null;
end if;

if not exists (select 1 from pg_constraint where conname = 'fk_loja_produtos_modelo_id') then
alter table public.loja_produtos
add constraint fk_loja_produtos_modelo_id
foreign key (modelo_id) references public.loja_modelos(id)
on delete set null;
end if;
end $$;

create index if not exists idx_loja_produtos_marca_id on public.loja_produtos(marca_id);
create index if not exists idx_loja_produtos_modelo_id on public.loja_produtos(modelo_id);

-- =========================================
-- 3) Variantes (SKU vendável) com FKs
-- =========================================
create table if not exists public.loja_produto_variantes (
id bigint generated by default as identity primary key,
produto_id bigint not null,
sku text not null, -- único e estável (vamos gerar automaticamente depois)
cor_id bigint,
numeracao_id bigint,
tamanho_id bigint,

estoque_atual integer not null default 0,
preco_venda_centavos integer, -- null = herda do produto base
ativo boolean not null default true,
observacoes text,
created_at timestamptz not null default now(),
updated_at timestamptz not null default now(),

constraint fk_loja_variantes_produto
foreign key (produto_id) references public.loja_produtos(id) on delete cascade,

constraint fk_loja_variantes_cor
foreign key (cor_id) references public.loja_cores(id) on delete set null,

constraint fk_loja_variantes_numeracao
foreign key (numeracao_id) references public.loja_numeracoes(id) on delete set null,

constraint fk_loja_variantes_tamanho
foreign key (tamanho_id) references public.loja_tamanhos(id) on delete set null
);

create unique index if not exists ux_loja_variantes_sku
on public.loja_produto_variantes (sku);

-- Índice composto para a busca que você citou: "produto + cor + numeração"
create index if not exists idx_loja_variantes_busca_calcado
on public.loja_produto_variantes (produto_id, cor_id, numeracao_id);

-- Índice composto para "produto + cor + tamanho"
create index if not exists idx_loja_variantes_busca_roupa
on public.loja_produto_variantes (produto_id, cor_id, tamanho_id);

create index if not exists idx_loja_variantes_produto_id on public.loja_produto_variantes(produto_id);

-- =========================================
-- 4) Regra de unicidade por combinação (evitar duplicar a mesma variante)
-- =========================================
-- Uma combinação (produto_id + cor_id + numeracao_id + tamanho_id) não deve se repetir.
-- Observação: NULLs em UNIQUE no Postgres permitem múltiplos registros; então fazemos index por COALESCE.
create unique index if not exists ux_loja_variantes_combo
on public.loja_produto_variantes (
produto_id,
coalesce(cor_id, 0),
coalesce(numeracao_id, 0),
coalesce(tamanho_id, 0)
);

commit;
