-- Conexao Danca -- Produto Educacional (canonico) + vinculo Turma/Matricula
-- Objetivo: separar "produto" (oferta) de "execucao" (turma)

BEGIN;

-- 1) Tabela canonica de produtos educacionais
CREATE TABLE IF NOT EXISTS public.escola_produtos_educacionais (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo text NOT NULL CHECK (tipo IN ('CURSO_REGULAR', 'CURSO_LIVRE', 'PROJETO_ARTISTICO')),
  titulo text NOT NULL,
  curso_id bigint NULL,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- FK opcional para cursos (somente quando for CURSO_REGULAR)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'escola_produtos_educacionais_curso_id_fkey'
  ) THEN
    ALTER TABLE public.escola_produtos_educacionais
      ADD CONSTRAINT escola_produtos_educacionais_curso_id_fkey
      FOREIGN KEY (curso_id) REFERENCES public.cursos(id)
      ON DELETE SET NULL;
  END IF;
END$$;

CREATE INDEX IF NOT EXISTS idx_escola_produtos_educacionais_tipo
  ON public.escola_produtos_educacionais(tipo);

CREATE INDEX IF NOT EXISTS idx_escola_produtos_educacionais_curso_id
  ON public.escola_produtos_educacionais(curso_id);

-- 2) Adicionar produto_id em turmas (execucao aponta para produto)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema='public' AND table_name='turmas' AND column_name='produto_id'
  ) THEN
    ALTER TABLE public.turmas ADD COLUMN produto_id bigint NULL;
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'turmas_produto_id_fkey'
  ) THEN
    ALTER TABLE public.turmas
      ADD CONSTRAINT turmas_produto_id_fkey
      FOREIGN KEY (produto_id) REFERENCES public.escola_produtos_educacionais(id)
      ON DELETE SET NULL;
  END IF;
END$$;

CREATE INDEX IF NOT EXISTS idx_turmas_produto_id
  ON public.turmas(produto_id);

-- 3) Backfill: criar produtos REGULAR a partir de cursos
INSERT INTO public.escola_produtos_educacionais (tipo, titulo, curso_id)
SELECT 'CURSO_REGULAR', c.nome, c.id
FROM public.cursos c
WHERE NOT EXISTS (
  SELECT 1 FROM public.escola_produtos_educacionais p
  WHERE p.tipo='CURSO_REGULAR' AND p.curso_id = c.id
);

-- 4) Backfill: mapear turmas REGULAR -> produto (casar turmas.curso (texto) com cursos.nome)
UPDATE public.turmas t
SET produto_id = p.id
FROM public.cursos c
JOIN public.escola_produtos_educacionais p
  ON p.tipo='CURSO_REGULAR' AND p.curso_id = c.id
WHERE
  t.tipo_turma = 'REGULAR'
  AND t.produto_id IS NULL
  AND lower(trim(t.curso)) = lower(trim(c.nome));

-- 5) Backfill: criar produtos CURSO_LIVRE por turma (produto = oferta daquele curso livre)
INSERT INTO public.escola_produtos_educacionais (tipo, titulo)
SELECT 'CURSO_LIVRE', t.nome
FROM public.turmas t
WHERE t.tipo_turma = 'CURSO_LIVRE'
  AND NOT EXISTS (
    SELECT 1
    FROM public.escola_produtos_educacionais p
    WHERE p.tipo='CURSO_LIVRE' AND lower(trim(p.titulo)) = lower(trim(t.nome))
  );

UPDATE public.turmas t
SET produto_id = p.id
FROM public.escola_produtos_educacionais p
WHERE
  t.tipo_turma = 'CURSO_LIVRE'
  AND t.produto_id IS NULL
  AND p.tipo='CURSO_LIVRE'
  AND lower(trim(p.titulo)) = lower(trim(t.nome));

-- 6) Adicionar produto_id em matriculas (canonico de preco)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema='public' AND table_name='matriculas' AND column_name='produto_id'
  ) THEN
    ALTER TABLE public.matriculas ADD COLUMN produto_id bigint NULL;
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'matriculas_produto_id_fkey'
  ) THEN
    ALTER TABLE public.matriculas
      ADD CONSTRAINT matriculas_produto_id_fkey
      FOREIGN KEY (produto_id) REFERENCES public.escola_produtos_educacionais(id)
      ON DELETE SET NULL;
  END IF;
END$$;

CREATE INDEX IF NOT EXISTS idx_matriculas_produto_id
  ON public.matriculas(produto_id);

-- 7) Backfill: matriculas(produto_id) a partir de turmas(produto_id) usando vinculo_id
UPDATE public.matriculas m
SET produto_id = t.produto_id
FROM public.turmas t
WHERE
  m.produto_id IS NULL
  AND m.vinculo_id IS NOT NULL
  AND t.turma_id = m.vinculo_id
  AND t.produto_id IS NOT NULL;

COMMIT;
