BEGIN;

-- Tabela de politicas de preco
CREATE TABLE IF NOT EXISTS public.financeiro_politicas_preco (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  descricao text NULL,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'financeiro_politicas_preco'
      AND column_name = 'politica_preco_id'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'financeiro_politicas_preco'
      AND column_name = 'id'
  ) THEN
    ALTER TABLE public.financeiro_politicas_preco
      RENAME COLUMN politica_preco_id TO id;
  END IF;
END $$;

-- Vincular tiers a politica
ALTER TABLE public.financeiro_tiers
  ADD COLUMN IF NOT EXISTS politica_id bigint NULL;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'financeiro_tiers'
      AND column_name = 'politica_preco_id'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'financeiro_tiers'
      AND column_name = 'politica_id'
  ) THEN
    ALTER TABLE public.financeiro_tiers
      RENAME COLUMN politica_preco_id TO politica_id;
  END IF;
END $$;

ALTER TABLE public.financeiro_tiers DROP CONSTRAINT IF EXISTS financeiro_tiers_politica_preco_fk;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'financeiro_tiers_politica_fk'
  ) THEN
    ALTER TABLE public.financeiro_tiers
      ADD CONSTRAINT financeiro_tiers_politica_fk
      FOREIGN KEY (politica_id)
      REFERENCES public.financeiro_politicas_preco(id)
      ON DELETE RESTRICT;
  END IF;
END $$;

DROP INDEX IF EXISTS idx_financeiro_tiers_politica_preco;

CREATE INDEX IF NOT EXISTS idx_financeiro_tiers_politica_lookup
  ON public.financeiro_tiers (politica_id, tabela_id, tabela_item_id, ativo, ordem);

-- Politica padrao por tabela/item
CREATE TABLE IF NOT EXISTS public.financeiro_politicas_preco_padrao (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tabela_id bigint NOT NULL,
  tabela_item_id bigint NOT NULL,
  politica_id bigint NOT NULL,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'financeiro_politicas_preco_padrao_tabela_fk'
  ) THEN
    ALTER TABLE public.financeiro_politicas_preco_padrao
      ADD CONSTRAINT financeiro_politicas_preco_padrao_tabela_fk
      FOREIGN KEY (tabela_id)
      REFERENCES public.matricula_tabelas(id)
      ON DELETE RESTRICT;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'financeiro_politicas_preco_padrao_item_fk'
  ) THEN
    ALTER TABLE public.financeiro_politicas_preco_padrao
      ADD CONSTRAINT financeiro_politicas_preco_padrao_item_fk
      FOREIGN KEY (tabela_item_id)
      REFERENCES public.matricula_tabela_itens(id)
      ON DELETE RESTRICT;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'financeiro_politicas_preco_padrao_politica_fk'
  ) THEN
    ALTER TABLE public.financeiro_politicas_preco_padrao
      ADD CONSTRAINT financeiro_politicas_preco_padrao_politica_fk
      FOREIGN KEY (politica_id)
      REFERENCES public.financeiro_politicas_preco(id)
      ON DELETE RESTRICT;
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS financeiro_politicas_preco_padrao_unq
  ON public.financeiro_politicas_preco_padrao (tabela_id, tabela_item_id)
  WHERE ativo = true;

-- Backfill: politica Padrao + atribuir tiers existentes
DO $$
DECLARE
  politica_padrao_id bigint;
BEGIN
  SELECT id INTO politica_padrao_id
  FROM public.financeiro_politicas_preco
  WHERE nome = 'Padrao'
  ORDER BY id
  LIMIT 1;

  IF politica_padrao_id IS NULL THEN
    INSERT INTO public.financeiro_politicas_preco (nome, descricao, ativo)
    VALUES ('Padrao', 'Politica padrao inicial', true)
    RETURNING id INTO politica_padrao_id;
  END IF;

  UPDATE public.financeiro_tiers
    SET politica_id = politica_padrao_id
  WHERE politica_id IS NULL;

  INSERT INTO public.financeiro_politicas_preco_padrao (tabela_id, tabela_item_id, politica_id, ativo)
  SELECT DISTINCT tabela_id, tabela_item_id, politica_padrao_id, true
  FROM public.financeiro_tiers
  WHERE tabela_id IS NOT NULL
    AND tabela_item_id IS NOT NULL
    AND politica_id = politica_padrao_id
  ON CONFLICT DO NOTHING;
END $$;

COMMIT;
