BEGIN;

CREATE TABLE IF NOT EXISTS public.matricula_eventos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  matricula_id BIGINT NOT NULL REFERENCES public.matriculas(id) ON DELETE CASCADE,
  tipo_evento TEXT NOT NULL,
  dados JSONB NOT NULL DEFAULT '{}'::jsonb,
  autorizado_por UUID,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'matricula_eventos_tipo_evento_chk'
      AND conrelid = 'public.matricula_eventos'::regclass
  ) THEN
    ALTER TABLE public.matricula_eventos
      ADD CONSTRAINT matricula_eventos_tipo_evento_chk
      CHECK (tipo_evento IN (
        'EXCECAO_PRIMEIRO_PAGAMENTO_CONCEDIDA',
        'EXCECAO_PRIMEIRO_PAGAMENTO_REVOGADA',
        'OBSERVACAO_INTERNA',
        'STATUS_ALTERADO'
      ));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_matricula_eventos_matricula
  ON public.matricula_eventos (matricula_id);

CREATE INDEX IF NOT EXISTS idx_matricula_eventos_tipo
  ON public.matricula_eventos (tipo_evento);

CREATE INDEX IF NOT EXISTS idx_matricula_eventos_criado_em
  ON public.matricula_eventos (criado_em DESC);

COMMIT;
