BEGIN;
-- 1) Grupo de Tier
CREATE TABLE IF NOT EXISTS public.financeiro_tier_grupos (
  tier_grupo_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  descricao text NULL,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
-- 2) Vincular Servico ao Grupo de Tier
ALTER TABLE public.escola_produtos_educacionais
ADD COLUMN IF NOT EXISTS tier_grupo_id bigint NULL;
ALTER TABLE public.escola_produtos_educacionais
ADD CONSTRAINT escola_produtos_educacionais_tier_grupo_id_fkey
FOREIGN KEY (tier_grupo_id)
REFERENCES public.financeiro_tier_grupos(tier_grupo_id)
ON DELETE SET NULL;
-- 3) Definicao dos Tiers
CREATE TABLE IF NOT EXISTS public.financeiro_tiers (
  tier_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tier_grupo_id bigint NOT NULL,
  ordem integer NOT NULL,
  valor_centavos integer NOT NULL,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.financeiro_tiers
ADD CONSTRAINT financeiro_tiers_tier_grupo_id_fkey
FOREIGN KEY (tier_grupo_id)
REFERENCES public.financeiro_tier_grupos(tier_grupo_id)
ON DELETE CASCADE;
CREATE UNIQUE INDEX IF NOT EXISTS uq_financeiro_tiers_ordem
ON public.financeiro_tiers(tier_grupo_id, ordem);
COMMIT;
