BEGIN;

-- 1) Itens precificaveis dentro de um servico
-- Ex.: Turma: "Mensalidade"
-- Ex.: Projeto: "Participacao", "Coreografia A", "Personagem X", "Figurino", "Video"
CREATE TABLE IF NOT EXISTS public.servico_itens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  servico_id BIGINT NOT NULL REFERENCES public.servicos(id) ON DELETE CASCADE,
  codigo TEXT NOT NULL,                  -- ex: MENSALIDADE, PARTICIPACAO, COREO_A, PERSONAGEM_X
  nome TEXT NOT NULL,                    -- label humano
  descricao TEXT NULL,
  tipo_item TEXT NOT NULL DEFAULT 'PADRAO',  -- PADRAO | COREOGRAFIA | PERSONAGEM | TAXA | EXTRA
  obrigatorio BOOLEAN NOT NULL DEFAULT false,
  ativo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_servico_itens_codigo
  ON public.servico_itens (servico_id, codigo);

-- 2) Precos dos itens (valor atual + historico)
CREATE TABLE IF NOT EXISTS public.servico_itens_precos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id BIGINT NOT NULL REFERENCES public.servico_itens(id) ON DELETE CASCADE,
  valor_centavos INTEGER NOT NULL,
  moeda TEXT NOT NULL DEFAULT 'BRL',
  vigencia_inicio DATE NULL,
  vigencia_fim DATE NULL,
  ativo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_servico_itens_precos_item
  ON public.servico_itens_precos (item_id);

-- 3) Itens escolhidos na matricula (o que sera cobrado/lancado)
CREATE TABLE IF NOT EXISTS public.matriculas_itens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  matricula_id BIGINT NOT NULL REFERENCES public.matriculas(id) ON DELETE CASCADE,
  item_id BIGINT NOT NULL REFERENCES public.servico_itens(id),
  quantidade INTEGER NOT NULL DEFAULT 1,
  valor_centavos INTEGER NOT NULL,       -- snapshot do valor no momento da matricula
  moeda TEXT NOT NULL DEFAULT 'BRL',
  observacoes TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_matriculas_itens_matricula
  ON public.matriculas_itens (matricula_id);

COMMIT;
