begin;

create table if not exists public.matricula_planos_pagamento (
  id bigint generated by default as identity primary key,

  titulo text not null,
  descricao text,

  periodicidade text not null, -- MENSAL / AVISTA / PARCELADO
  numero_parcelas integer not null default 1,

  permite_prorata boolean not null default true,
  ativo boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid,
  updated_by uuid
);

-- Checks
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'matricula_planos_pagamento_periodicidade_chk'
      and conrelid = 'public.matricula_planos_pagamento'::regclass
  ) then
    alter table public.matricula_planos_pagamento
      add constraint matricula_planos_pagamento_periodicidade_chk
      check (periodicidade in ('MENSAL','AVISTA','PARCELADO'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'matricula_planos_pagamento_num_parcelas_chk'
      and conrelid = 'public.matricula_planos_pagamento'::regclass
  ) then
    alter table public.matricula_planos_pagamento
      add constraint matricula_planos_pagamento_num_parcelas_chk
      check (numero_parcelas between 1 and 36);
  end if;
end $$;

-- Indices
create index if not exists idx_mpp_ativo on public.matricula_planos_pagamento (ativo);
create index if not exists idx_mpp_periodicidade on public.matricula_planos_pagamento (periodicidade);
create index if not exists idx_mpp_titulo on public.matricula_planos_pagamento (titulo);

commit;
