BEGIN;

-- 1) Unidade de Execucao (canonico)
-- - Representa qualquer subdivisao do "servico" (turma, grupo, elenco, coreografia, personagem...)
-- - Neste momento, fazemos backfill a partir de turmas (origem_tipo='TURMA').

CREATE TABLE IF NOT EXISTS public.escola_unidades_execucao (
  unidade_execucao_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  servico_id bigint NOT NULL, -- referencia escola_produtos_educacionais.id (servico canonico atual)
  denominacao text NOT NULL,  -- ex.: "Turma", "Grupo", "Elenco", "Coreografia", "Personagem"
  nome text NOT NULL,         -- ex.: nome exibivel ("Ballet Manha", "Coreografia A")
  origem_tipo text NOT NULL CHECK (origem_tipo IN ('TURMA', 'GRUPO', 'ELENCO', 'COREOGRAFIA', 'PERSONAGEM', 'OUTRO')),
  origem_id bigint NULL,      -- quando origem_tipo='TURMA' -> turmas.turma_id
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- FK para servico (tabela ja existente)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'escola_unidades_execucao_servico_id_fkey') THEN
    ALTER TABLE public.escola_unidades_execucao
      ADD CONSTRAINT escola_unidades_execucao_servico_id_fkey
      FOREIGN KEY (servico_id) REFERENCES public.escola_produtos_educacionais(id)
      ON DELETE CASCADE;
  END IF;
END$$;

CREATE INDEX IF NOT EXISTS idx_escola_unidades_execucao_servico_id
  ON public.escola_unidades_execucao(servico_id);

CREATE INDEX IF NOT EXISTS idx_escola_unidades_execucao_origem
  ON public.escola_unidades_execucao(origem_tipo, origem_id);

-- Unicidade para evitar duplicar a mesma origem dentro do mesmo servico
CREATE UNIQUE INDEX IF NOT EXISTS uq_escola_unidades_execucao_origem
  ON public.escola_unidades_execucao(servico_id, origem_tipo, origem_id);

-- 2) Backfill: criar Unidade de Execucao a partir de turmas
-- Pressuposto: turmas.produto_id ja existe e esta preenchido (servico_id = produto_id)
INSERT INTO public.escola_unidades_execucao (servico_id, denominacao, nome, origem_tipo, origem_id)
SELECT
  t.produto_id as servico_id,
  'Turma' as denominacao,
  t.nome as nome,
  'TURMA' as origem_tipo,
  t.turma_id as origem_id
FROM public.turmas t
WHERE t.produto_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1
    FROM public.escola_unidades_execucao ue
    WHERE ue.servico_id = t.produto_id
      AND ue.origem_tipo = 'TURMA'
      AND ue.origem_id = t.turma_id
  );

-- 3) Pivot: Tabela de Precos -> Unidades de Execucao (0..N)
-- Regra de interpretacao:
-- - se nao houver linhas para tabela_id => tabela vale para TODAS as unidades daquele servico
CREATE TABLE IF NOT EXISTS public.matricula_tabelas_unidades_execucao (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tabela_id bigint NOT NULL,
  unidade_execucao_id bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'matricula_tabelas_unidades_execucao_tabela_id_fkey') THEN
    ALTER TABLE public.matricula_tabelas_unidades_execucao
      ADD CONSTRAINT matricula_tabelas_unidades_execucao_tabela_id_fkey
      FOREIGN KEY (tabela_id) REFERENCES public.matricula_tabelas(id)
      ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'matricula_tabelas_unidades_execucao_unidade_execucao_id_fkey'
  ) THEN
    ALTER TABLE public.matricula_tabelas_unidades_execucao
      ADD CONSTRAINT matricula_tabelas_unidades_execucao_unidade_execucao_id_fkey
      FOREIGN KEY (unidade_execucao_id) REFERENCES public.escola_unidades_execucao(unidade_execucao_id)
      ON DELETE CASCADE;
  END IF;
END$$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_matricula_tabelas_unidades_execucao
  ON public.matricula_tabelas_unidades_execucao(tabela_id, unidade_execucao_id);

CREATE INDEX IF NOT EXISTS idx_matricula_tabelas_unidades_execucao_tabela
  ON public.matricula_tabelas_unidades_execucao(tabela_id);

COMMIT;
