-- Tabela de auditoria de estoque (livro de movimentos)
create table if not exists public.loja_estoque_movimentos (
  id bigint generated by default as identity primary key,
  produto_id bigint not null references public.loja_produtos(id) on delete cascade,
  tipo text not null check (tipo in ('ENTRADA','SAIDA','AJUSTE')),
  quantidade integer not null check (quantidade > 0),
  origem text not null check (origem in ('COMPRA','VENDA','CANCELAMENTO_VENDA','AJUSTE_MANUAL')),
  referencia_id bigint,
  observacao text,
  saldo_antes integer,
  saldo_depois integer,
  custo_unitario_centavos integer,
  created_by uuid,
  created_at timestamptz not null default now()
);

create index if not exists idx_loja_estoque_mov_produto on public.loja_estoque_movimentos(produto_id);
create index if not exists idx_loja_estoque_mov_origem on public.loja_estoque_movimentos(origem, referencia_id);
