-- Conexao Danca - Contratos MVP
-- Cria: contratos_modelo, contratos_emitidos e relacionamento opcional com termos
-- Observacao: MVP sem assinatura digital e sem PDF obrigatorio (pdf_url reservado)

begin;

-- 1) Tabela de modelos
create table if not exists public.contratos_modelo (
  id bigint generated by default as identity primary key,
  tipo_contrato text not null, -- REGULAR | CURSO_LIVRE | PROJETO_ARTISTICO | ACESSORIO (futuro)
  titulo text not null,
  versao text not null default 'v1.0',
  ativo boolean not null default true,
  texto_modelo_md text not null,
  placeholders_schema_json jsonb not null default '[]'::jsonb,
  observacoes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_contratos_modelo_tipo_ativo
  on public.contratos_modelo (tipo_contrato, ativo);

-- 2) Tabela de emitidos
create table if not exists public.contratos_emitidos (
  id bigint generated by default as identity primary key,
  matricula_id bigint not null, -- FK adicionada abaixo (matriculas)
  contrato_modelo_id bigint not null references public.contratos_modelo(id) on delete restrict,
  status_assinatura text not null default 'PENDENTE', -- PENDENTE | ASSINADO | CANCELADO
  conteudo_renderizado_md text not null,
  variaveis_utilizadas_json jsonb not null default '{}'::jsonb,
  snapshot_financeiro_json jsonb not null default '{}'::jsonb,
  hash_conteudo text,
  pdf_url text,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_contratos_emitidos_matricula
  on public.contratos_emitidos (matricula_id);

create index if not exists idx_contratos_emitidos_status
  on public.contratos_emitidos (status_assinatura);

-- 3) FK para matriculas (assume public.matriculas)
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'contratos_emitidos_matricula_fk'
  ) then
    alter table public.contratos_emitidos
      add constraint contratos_emitidos_matricula_fk
      foreign key (matricula_id) references public.matriculas(id)
      on delete restrict;
  end if;
end $$;

-- 4) (Opcional MVP) N:N com termos acessorios (futuro)
create table if not exists public.contratos_emitidos_termos (
  contrato_emitido_id bigint not null references public.contratos_emitidos(id) on delete cascade,
  termo_modelo_id bigint not null, -- reserva para integrar com contratos_acessorios_modelo
  versao text,
  created_at timestamptz not null default now(),
  primary key (contrato_emitido_id, termo_modelo_id)
);

-- 5) Trigger simples de updated_at
create or replace function public.contratos_set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_contratos_modelo_updated_at on public.contratos_modelo;
create trigger trg_contratos_modelo_updated_at
before update on public.contratos_modelo
for each row execute function public.contratos_set_updated_at();

drop trigger if exists trg_contratos_emitidos_updated_at on public.contratos_emitidos;
create trigger trg_contratos_emitidos_updated_at
before update on public.contratos_emitidos
for each row execute function public.contratos_set_updated_at();

commit;

select pg_notify('pgrst', 'reload schema');
