-- FIX: criacao das tabelas de preco do Cafe sem constraint com expressao
-- Motivo: Postgres nao permite UNIQUE constraint com expressao no CREATE TABLE.
-- Solucao: UNIQUE INDEX com expressao.

begin;

create table if not exists public.cafe_tabelas_preco (
  id bigint generated by default as identity primary key,
  codigo text not null,
  nome text not null,
  descricao text null,
  ativo boolean not null default true,
  is_default boolean not null default false,
  ordem integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Unique por codigo normalizado (expressao) via index
create unique index if not exists ux_cafe_tabelas_preco_codigo_norm
  on public.cafe_tabelas_preco (upper(trim(both from codigo)));

create table if not exists public.cafe_produto_precos (
  id bigint generated by default as identity primary key,
  produto_id bigint not null references public.cafe_produtos(id) on delete cascade,
  tabela_preco_id bigint not null references public.cafe_tabelas_preco(id) on delete cascade,
  preco_centavos integer not null default 0,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ux_cafe_produto_precos unique (produto_id, tabela_preco_id)
);

create index if not exists idx_cafe_produto_precos_produto on public.cafe_produto_precos (produto_id);
create index if not exists idx_cafe_produto_precos_tabela on public.cafe_produto_precos (tabela_preco_id);

alter table public.cafe_vendas
  add column if not exists tabela_preco_id bigint null references public.cafe_tabelas_preco(id) on delete set null;

-- Seed inicial: ALUNO (default) + COLABORADOR
insert into public.cafe_tabelas_preco (codigo, nome, descricao, ativo, is_default, ordem)
select 'ALUNO', 'Preco Aluno (Padrao)', 'Tabela padrao para alunos no dia a dia.', true, true, 0
where not exists (
  select 1 from public.cafe_tabelas_preco where upper(trim(codigo)) = 'ALUNO'
);

insert into public.cafe_tabelas_preco (codigo, nome, descricao, ativo, is_default, ordem)
select 'COLABORADOR', 'Preco Colaborador', 'Tabela para colaboradores.', true, false, 1
where not exists (
  select 1 from public.cafe_tabelas_preco where upper(trim(codigo)) = 'COLABORADOR'
);

commit;
