-- Compras de insumos do Ballet Cafe (modelo simplificado)
-- Fornecedor/local: texto livre
-- Cada compra gera movimento financeiro (despesa) e entrada de estoque (insumo_movimentos)

create table if not exists public.cafe_compras (
  id bigint generated by default as identity primary key,
  centro_custo_id bigint not null references public.centros_custo(id) on delete restrict,
  conta_financeira_id bigint not null references public.contas_financeiras(id) on delete restrict,
  categoria_financeira_id bigint null references public.categorias_financeiras(id) on delete set null,
  onde_comprei text not null,
  data_compra date not null default current_date,
  valor_total_centavos integer not null default 0,
  movimento_financeiro_id bigint null references public.movimento_financeiro(id) on delete set null,
  observacoes text null,
  created_by uuid null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_cafe_compras_data on public.cafe_compras (data_compra desc);

create table if not exists public.cafe_compra_itens (
  id bigint generated by default as identity primary key,
  compra_id bigint not null references public.cafe_compras(id) on delete cascade,
  insumo_id bigint not null references public.cafe_insumos(id) on delete restrict,
  quantidade numeric not null,
  valor_total_centavos integer not null default 0,
  custo_unitario_centavos integer not null default 0,
  validade date null,
  observacoes text null,
  created_at timestamptz not null default now()
);

create index if not exists idx_cafe_compra_itens_compra on public.cafe_compra_itens (compra_id);
create index if not exists idx_cafe_compra_itens_insumo on public.cafe_compra_itens (insumo_id);

-- triggers updated_at (se funcao padrao existir)
do $$
begin
  if exists (select 1 from pg_proc where proname = 'set_updated_at') then
    if not exists (
      select 1 from pg_trigger t
      join pg_class c on c.oid = t.tgrelid
      join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = 'public' and c.relname = 'cafe_compras' and t.tgname = 'trg_cafe_compras_set_updated_at'
    ) then
      create trigger trg_cafe_compras_set_updated_at
      before update on public.cafe_compras
      for each row execute function public.set_updated_at();
    end if;
  end if;
end $$;
