-- Academico — Periodo Letivo (MVP)
-- Faixas + Excecoes (feriados/ponto facultativo/sem aula) para a ESCOLA
-- Data: 2026-01-06

BEGIN;

-- 1) Faixas do Periodo Letivo (intervalos oficiais)
CREATE TABLE IF NOT EXISTS public.periodos_letivos_faixas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  periodo_letivo_id BIGINT NOT NULL REFERENCES public.periodos_letivos (id) ON DELETE CASCADE,

  -- Classificacao hierarquica (Dominio -> Categoria -> Subcategoria)
  -- Dominio fixo para este contexto: ACADEMICO
  dominio TEXT NOT NULL DEFAULT 'ACADEMICO',
  categoria TEXT NOT NULL,          -- ex.: SEMESTRE | FERIAS | RECESSO | AVALIACOES | EVENTO_INSTITUCIONAL
  subcategoria TEXT,                -- ex.: SEMESTRE_1 | SEMESTRE_2

  titulo TEXT NOT NULL,
  descricao TEXT,

  data_inicio DATE NOT NULL,
  data_fim DATE NOT NULL,

  -- Flags uteis para calendario
  sem_aula BOOLEAN NOT NULL DEFAULT FALSE,
  em_avaliacao BOOLEAN NOT NULL DEFAULT FALSE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pl_faixas_periodo
  ON public.periodos_letivos_faixas (periodo_letivo_id);

CREATE INDEX IF NOT EXISTS idx_pl_faixas_datas
  ON public.periodos_letivos_faixas (data_inicio, data_fim);

CREATE INDEX IF NOT EXISTS idx_pl_faixas_classificacao
  ON public.periodos_letivos_faixas (categoria, subcategoria);

COMMIT;
