-- Calendario MVP: periodo letivo + itens institucionais
-- Data: 2026-01-06

BEGIN;

CREATE TABLE IF NOT EXISTS public.periodos_letivos (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo               TEXT NOT NULL,
  titulo               TEXT NOT NULL,
  ano_referencia       INTEGER NOT NULL,
  data_inicio          DATE NOT NULL,
  data_fim             DATE NOT NULL,
  inicio_letivo_janeiro DATE,
  ativo                BOOLEAN NOT NULL DEFAULT TRUE,
  observacoes          TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by           UUID,
  updated_by           UUID
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_periodos_letivos_codigo
  ON public.periodos_letivos (codigo);

CREATE INDEX IF NOT EXISTS idx_periodos_letivos_ano
  ON public.periodos_letivos (ano_referencia);

-- FK em turmas.periodo_letivo_id (se existir)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema='public' AND table_name='turmas' AND column_name='periodo_letivo_id'
  ) THEN
    IF NOT EXISTS (
      SELECT 1
      FROM pg_constraint
      WHERE conname = 'fk_turmas_periodo_letivo'
    ) THEN
      ALTER TABLE public.turmas
        ADD CONSTRAINT fk_turmas_periodo_letivo
        FOREIGN KEY (periodo_letivo_id)
        REFERENCES public.periodos_letivos (id)
        ON DELETE SET NULL;
    END IF;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.calendario_itens_institucionais (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  periodo_letivo_id BIGINT REFERENCES public.periodos_letivos (id) ON DELETE SET NULL,

  dominio           TEXT NOT NULL,
  categoria         TEXT NOT NULL,
  subcategoria      TEXT,

  titulo            TEXT NOT NULL,
  descricao         TEXT,

  data_inicio       DATE NOT NULL,
  data_fim          DATE,

  sem_aula          BOOLEAN NOT NULL DEFAULT FALSE,
  ponto_facultativo BOOLEAN NOT NULL DEFAULT FALSE,
  em_avaliacao      BOOLEAN NOT NULL DEFAULT FALSE,

  visibilidade      TEXT NOT NULL DEFAULT 'ESCOLA', -- ESCOLA | ADMIN | PUBLICO (MVP)

  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by        UUID,
  updated_by        UUID
);

CREATE INDEX IF NOT EXISTS idx_calendario_itens_periodo
  ON public.calendario_itens_institucionais (periodo_letivo_id);

CREATE INDEX IF NOT EXISTS idx_calendario_itens_datas
  ON public.calendario_itens_institucionais (data_inicio, data_fim);

CREATE INDEX IF NOT EXISTS idx_calendario_itens_classificacao
  ON public.calendario_itens_institucionais (dominio, categoria, subcategoria);

COMMIT;
