-- Tabelas de preco do Cafe + precos por produto
-- Estrutura pensada para: ALUNO, COLABORADOR, EVENTO, etc.

create table if not exists public.cafe_tabelas_preco (
  id bigint generated by default as identity primary key,
  codigo text not null,
  nome text not null,
  descricao text null,
  ativo boolean not null default true,
  is_default boolean not null default false,
  ordem integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ux_cafe_tabelas_preco_codigo unique (upper(trim(both from codigo)))
);

create table if not exists public.cafe_produto_precos (
  id bigint generated by default as identity primary key,
  produto_id bigint not null references public.cafe_produtos(id) on delete cascade,
  tabela_preco_id bigint not null references public.cafe_tabelas_preco(id) on delete cascade,
  preco_centavos integer not null default 0,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ux_cafe_produto_precos unique (produto_id, tabela_preco_id)
);

create index if not exists idx_cafe_produto_precos_produto on public.cafe_produto_precos(produto_id);
create index if not exists idx_cafe_produto_precos_tabela on public.cafe_produto_precos(tabela_preco_id);

-- Persistir tabela de preco usada na venda (auditoria e relatorio)
alter table public.cafe_vendas
  add column if not exists tabela_preco_id bigint null references public.cafe_tabelas_preco(id) on delete set null;

-- Seed inicial: ALUNO (default) + COLABORADOR
insert into public.cafe_tabelas_preco (codigo, nome, descricao, ativo, is_default, ordem)
select 'ALUNO', 'Preco Aluno (Padrao)', 'Tabela padrao para alunos no dia a dia.', true, true, 0
where not exists (
  select 1 from public.cafe_tabelas_preco where upper(trim(codigo)) = 'ALUNO'
);

insert into public.cafe_tabelas_preco (codigo, nome, descricao, ativo, is_default, ordem)
select 'COLABORADOR', 'Preco Colaborador', 'Tabela para colaboradores.', true, false, 1
where not exists (
  select 1 from public.cafe_tabelas_preco where upper(trim(codigo)) = 'COLABORADOR'
);

-- Trigger updated_at (usar funcao padrao public.set_updated_at() se existir)
do $$
begin
  if exists (select 1 from pg_proc where proname = 'set_updated_at') then
    if not exists (
      select 1
      from pg_trigger t
      join pg_class c on c.oid = t.tgrelid
      join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = 'public'
        and c.relname = 'cafe_tabelas_preco'
        and t.tgname = 'trg_cafe_tabelas_preco_set_updated_at'
    ) then
      create trigger trg_cafe_tabelas_preco_set_updated_at
      before update on public.cafe_tabelas_preco
      for each row execute function public.set_updated_at();
    end if;

    if not exists (
      select 1
      from pg_trigger t
      join pg_class c on c.oid = t.tgrelid
      join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = 'public'
        and c.relname = 'cafe_produto_precos'
        and t.tgname = 'trg_cafe_produto_precos_set_updated_at'
    ) then
      create trigger trg_cafe_produto_precos_set_updated_at
      before update on public.cafe_produto_precos
      for each row execute function public.set_updated_at();
    end if;
  end if;
end $$;
