begin;

-- Ballet Cafe MVP: Insumos, Produtos/Receitas, Vendas
-- Sem compras/pedidos de insumo (abastecimento manual via movimentos)

create table if not exists public.cafe_insumos (
  id bigint generated by default as identity primary key,
  nome text not null,
  unidade_base text not null, -- 'g' | 'ml' | 'un'
  controla_validade boolean not null default false,
  validade_dias_padrao integer null,
  custo_unitario_estimado_centavos integer not null default 0,
  saldo_atual numeric not null default 0,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists ux_cafe_insumos_nome
on public.cafe_insumos (upper(trim(both from nome)));

create table if not exists public.cafe_insumo_movimentos (
  id bigint generated by default as identity primary key,
  insumo_id bigint not null references public.cafe_insumos(id) on delete restrict,
  tipo text not null, -- 'ENTRADA' | 'SAIDA' | 'AJUSTE'
  quantidade numeric not null,
  custo_unitario_centavos integer null,
  validade date null,
  origem text not null default 'MANUAL', -- 'MANUAL' | 'VENDA' | 'OUTRO'
  referencia_id bigint null,
  observacoes text null,
  created_by uuid null references auth.users(id),
  created_at timestamptz not null default now()
);

create index if not exists idx_cafe_insumo_movimentos_insumo_data
on public.cafe_insumo_movimentos (insumo_id, created_at desc);

create table if not exists public.cafe_produtos (
  id bigint generated by default as identity primary key,
  nome text not null,
  categoria text not null default 'GERAL',
  unidade_venda text not null default 'un',
  preco_venda_centavos integer not null default 0,
  preparado boolean not null default true,
  insumo_direto_id bigint null references public.cafe_insumos(id) on delete set null,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists ux_cafe_produtos_nome
on public.cafe_produtos (upper(trim(both from nome)));

create table if not exists public.cafe_produto_receitas (
  id bigint generated by default as identity primary key,
  produto_id bigint not null references public.cafe_produtos(id) on delete cascade,
  insumo_id bigint not null references public.cafe_insumos(id) on delete restrict,
  quantidade numeric not null,
  unidade text not null, -- normalmente igual a unidade_base do insumo
  ordem integer not null default 0,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists ux_cafe_produto_receitas_produto_insumo
on public.cafe_produto_receitas (produto_id, insumo_id);

create table if not exists public.cafe_vendas (
  id bigint generated by default as identity primary key,
  pagador_pessoa_id bigint null references public.pessoas(id) on delete set null,
  consumidor_pessoa_id bigint null references public.pessoas(id) on delete set null,
  valor_total_centavos integer not null default 0,
  forma_pagamento text not null, -- 'PIX' | 'DINHEIRO' | 'CARTAO_CONEXAO_ALUNO' | 'CARTAO_CONEXAO_COLABORADOR'
  status_pagamento text not null default 'PAGO', -- 'PAGO' | 'PENDENTE'
  cobranca_id bigint null references public.cobrancas(id) on delete set null,
  observacoes text null,
  created_by uuid null references auth.users(id),
  created_at timestamptz not null default now()
);

create index if not exists idx_cafe_vendas_created_at
on public.cafe_vendas (created_at desc);

create table if not exists public.cafe_venda_itens (
  id bigint generated by default as identity primary key,
  venda_id bigint not null references public.cafe_vendas(id) on delete cascade,
  produto_id bigint not null references public.cafe_produtos(id) on delete restrict,
  quantidade numeric not null default 1,
  preco_unitario_centavos integer not null default 0,
  total_centavos integer not null default 0
);

create index if not exists idx_cafe_venda_itens_venda
on public.cafe_venda_itens (venda_id);

-- Trigger updated_at (usar funcao padrao se ja existir)
do $$
begin
  if exists (select 1 from pg_proc where proname = 'set_updated_at') then
    if not exists (
      select 1
      from pg_trigger t
      join pg_class c on c.oid = t.tgrelid
      join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = 'public'
        and c.relname = 'cafe_insumos'
        and t.tgname = 'trg_cafe_insumos_set_updated_at'
    ) then
      create trigger trg_cafe_insumos_set_updated_at
      before update on public.cafe_insumos
      for each row
      execute function public.set_updated_at();
    end if;

    if not exists (
      select 1
      from pg_trigger t
      join pg_class c on c.oid = t.tgrelid
      join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = 'public'
        and c.relname = 'cafe_produtos'
        and t.tgname = 'trg_cafe_produtos_set_updated_at'
    ) then
      create trigger trg_cafe_produtos_set_updated_at
      before update on public.cafe_produtos
      for each row
      execute function public.set_updated_at();
    end if;

    if not exists (
      select 1
      from pg_trigger t
      join pg_class c on c.oid = t.tgrelid
      join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = 'public'
        and c.relname = 'cafe_produto_receitas'
        and t.tgname = 'trg_cafe_produto_receitas_set_updated_at'
    ) then
      create trigger trg_cafe_produto_receitas_set_updated_at
      before update on public.cafe_produto_receitas
      for each row
      execute function public.set_updated_at();
    end if;
  end if;
end $$;

commit;
