-- Calendario MVP: eventos internos com datetime
-- Data: 2026-01-06

BEGIN;

CREATE TABLE IF NOT EXISTS public.eventos_internos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  periodo_letivo_id BIGINT REFERENCES public.periodos_letivos (id) ON DELETE SET NULL,

  dominio TEXT NOT NULL,
  categoria TEXT NOT NULL,
  subcategoria TEXT,

  titulo TEXT NOT NULL,
  descricao TEXT,

  inicio TIMESTAMPTZ NOT NULL,
  fim TIMESTAMPTZ,

  local TEXT,
  formato TEXT NOT NULL DEFAULT 'PRESENCIAL', -- PRESENCIAL | ONLINE | HIBRIDO (MVP)

  status TEXT NOT NULL DEFAULT 'AGENDADO',    -- AGENDADO | CANCELADO | CONCLUIDO (MVP)
  origem_tipo TEXT NOT NULL DEFAULT 'MANUAL', -- MANUAL | SISTEMA (MVP)

  visibilidade TEXT NOT NULL DEFAULT 'ADMIN', -- ADMIN | EQUIPE | PAIS (MVP)

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by UUID,
  updated_by UUID
);

CREATE INDEX IF NOT EXISTS idx_eventos_internos_periodo
  ON public.eventos_internos (periodo_letivo_id);

CREATE INDEX IF NOT EXISTS idx_eventos_internos_inicio_fim
  ON public.eventos_internos (inicio, fim);

CREATE INDEX IF NOT EXISTS idx_eventos_internos_classificacao
  ON public.eventos_internos (dominio, categoria, subcategoria);

COMMIT;
