ALTER TABLE public.matriculas
ADD COLUMN IF NOT EXISTS status_fluxo TEXT NOT NULL DEFAULT 'AGUARDANDO_LIQUIDACAO';

COMMENT ON COLUMN public.matriculas.status_fluxo IS
'RASCUNHO | AGUARDANDO_LIQUIDACAO | ATIVA | ENCERRADA';
